name: movie_viewing_app
description: Flutter Movie App Design Challenge

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  equatable: ^2.0.3
  shared_preferences: ^2.0.15
  motion_sensors: ^0.1.0
  vector_math: ^2.1.2
  share_plus: ^4.0.10+1
  floating: ^1.1.0
  quick_actions: ^0.6.0+11
  youtube_player_flutter: ^8.1.0
  video_player: ^2.4.6
  wakelock: ^0.6.2
  rive: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/icons/
    - assets/images/actors/
    - assets/images/movies/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/logo.jpg"
